### ISSUE TITLE
Keyboard mapping issues

### ISSUE THREAD

**Issue by tomxp411** [MiSTer-devel/MultiComp_MiSTer#1]
I know this is trivial, but the @ and " are swapped when using a US keyboard. I have to press Shift-2 to get " and shift-' to get @.

It would be nice if there was a way to either configure the core to swap those two symbols, or to maybe get core with those symbols in the expected location. 

Other symbols are also not correct on any keyboard:
The backslash and pipe (\ and |) do not do anything. The tilde (~, or shifted `) also doesn't print anything.

**Comment by fred-vaneijk** [comment]
Yes, this is related to the fact that the keyboard wants to be a UK not US mapping.  The plan is to change the keyboard to a US mapping.

**Comment by fred-vaneijk** [comment]
latest update fixes the keymap to make it a US mapping
