### ISSUE TITLE
Using the MiSTer Serial Terminal/Console

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/MultiComp_MiSTer#10]
Hello,

I'm having trouble connecting in Terminal/Console mode via SSH.
The command "screen /dev/ttyS1 115200" doesn't work as expected:
I occasionally see the console output, but the keyboard input doesn't work.

Remark: This same command works perfectly under the same conditions with the VT52_MiSTer core!

**Comment by fred-vaneijk** [comment]
Based on my testing the only microcomputer that works through SSH (or any other remote terminal) is CPM or BASIC/Interpreter mode under the Z80-CP/M CPU-ROM.  I think the others are using the wrong UART based on the investigation I have done so far.  I'm hoping to come up with a fix for those (may add an OSD option for local/remote terminal).

Which microcomputer are you using that is unreliable?  If you are using the Z80-CP/M what are you configuring for baud and flow control in the OSD?  I just tested with 115200 and no flow control and it seems ok (note you do need to press the space in the SSH console to let the core know which console it should be using).  Also make sure Serial Port is selected as Console Port.

If it gets in a bad state i.e. you don't see the 'Press [space] to activate console' message on the SSH terminal after reset try a full reset of the MiSTer and try again, I did notice once something got in a bad state and I had to do a full reset.

**Comment by kaloun34** [comment]
here is my configuration :

![IMG_4902](https://github.com/user-attachments/assets/0f55518b-0cd7-4d6d-b816-0f310546bdb8)

**Comment by kaloun34** [comment]
I've figured out what the problem was!
It was my MT-32 Pi connected to the user port that caused the conflict.
I should have thought of that before creating an issue.

**Comment by fred-vaneijk** [comment]
Great, glad you found the issue.  I'll close it.  Still looking at the image controller issue.

Thanks for taking a look at the core...

________________________________
