### ISSUE TITLE
Dead links to Grant Searle's website

### ISSUE THREAD

**Issue by ojaksch** [MiSTer-devel/MultiComp_MiSTer#6]
README should be fixed. The new links are

Using CP/M - from Grant Searle website:
http://searle.hostei.com/grant/Multicomp/cpm/fpgaCPM.html#UsingTheMachine

URL
[Grant's MULTICOMP pick and mix computer](http://searle.hostei.com/grant/Multicomp/index.html)

**Comment by hsnewman** [comment]
Those links don't work

**Comment by NEO-JAMMA** [comment]
Fixed in the Readme

**Comment by NEO-JAMMA** [comment]
Readme updated
