### ISSUE TITLE
OSD Menu inversion

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/MultiComp_MiSTer#9]
Hello,

In the "Storage Configuration" menu, I have to select "SD Controller" to use my CPM image from the Games/MultiComp directory. 
Isn't there an inversion with "Image Controller"?

**Comment by fred-vaneijk** [comment]
Both SD controllers will work with the Games/MultiComp directory.  The thing that differentiates them is the SD Controller can use the secondary SD Card if it is available, plugged in and formatted properly.  The Image control will only work with the Games/MultiComp directory.  Sorry for the confusion.  The Image Controller was added as a simpler internal way to use the image file in the Games/MultiComp directory.  We may be able to remove the Image Controller.

**Comment by kaloun34** [comment]
Ok, but when I select "Image Controller",  I can't boot from my disk image.

**Comment by fred-vaneijk** [comment]
yes, thanks, I see that now.  I will remove the Image controller option from the OSD as I don't think we need it.

**Comment by fred-vaneijk** [comment]
image controller option is removed
